# For an intro guide see: https://docs.github.com/en/actions/quickstart
# For a detailed guide: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows

name: Exercise Tests
on:
  - push # Run this workflow every time we push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: # Define multiple configurations to test on
        python-version: [3.7, 3.8, 3.9]

    # For each configuration defined above, run the following steps
    # sequentially.
    steps:
    - name: Checkout repository # Name of the step
      uses: actions/checkout@v2 # Use someone elses "action" to perform something
                                # (in this case checkout out our repo)

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install -r requirements.txt # Runs in the command line during this step

    - name: Install
      run: pip install .
    
    # - name: Test
    #   run: #ADD TEST commands here

    # - name: Codecov
    #   uses: codecov/codecov-action@v1
    #   with:
    #     name: exercise-codecov
    #     token:  # PUT YOUR TOKEN HERE
    #     fail_ci_if_error: true
